// state arguement is not the application state,
// but only the state this reducer cares about,
// listens for and is repsonsible for
// its the same state generated by the hotel_reducer
// now if the state is not available, then set it to 
// null - this is ES6 syntax

export default function(state=null, action) {
	switch(action.type) {
		case 'HOTEL_SELECTED':
		return action.payload;
	}

	return state;
}